version: "3.8"
services:
  postgresql:
    image: bitnami/postgresql:15.2.0
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/bitnami/postgresql
    ports:
      - 8432:5432
    environment:
      - POSTGRESQL_PASSWORD=test123
    networks:
      - teachergpt

  pgadmin:
    image: dpage/pgadmin4:6.21
    restart: unless-stopped
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - 8050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=hello@digital4you.ch
      - PGADMIN_DEFAULT_PASSWORD=d4y
    networks:
      - teachergpt

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    # command: >
    #   redis-server
    #   --loadmodule /opt/redis-stack/lib/redisearch.so
    #   --loadmodule /opt/redis-stack/lib/rejson.so
    #   --save ""
    #   --appendonly no
    #   --protected-mode no
    ports:
      - 8379:6379
      - 8001:8001
    networks:
      - teachergpt
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./data/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - teachergpt
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./data/etcd/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - teachergpt

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.5
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./data/etcd/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - teachergpt
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.18.3
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      SUM_INFERENCE_API: 'http://sum-transformers:8080'
      OPENAI_APIKEY: $OPENAI_APIKEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,sum-transformers,ref2vec-centroid,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    networks:
      - teachergpt
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    environment:
      ENABLE_CUDA: '0'
    networks:
      - teachergpt
  sum-transformers:
    image: semitechnologies/sum-transformers:facebook-bart-large-cnn-1.0.0
    environment:
      ENABLE_CUDA: '0'
    networks:
      - teachergpt
networks:
  teachergpt:
    driver: bridge
