version: "3.8"
services:
  postgresql:
    image: bitnami/postgresql:15.2.0
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/bitnami/postgresql
    ports:
      - 8432:5432
    environment:
      - POSTGRESQL_PASSWORD=test123
    networks:
      - teachergpt

  pgadmin:
    image: dpage/pgadmin4:6.21
    restart: unless-stopped
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - 8050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=hello@digital4you.ch
      - PGADMIN_DEFAULT_PASSWORD=d4y
    networks:
      - teachergpt

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    # command: >
    #   redis-server
    #   --loadmodule /opt/redis-stack/lib/redisearch.so
    #   --loadmodule /opt/redis-stack/lib/rejson.so
    #   --save ""
    #   --appendonly no
    #   --protected-mode no
    ports:
      - 8379:6379
      - 8001:8001
    networks:
      - teachergpt

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - ASR_MODEL=base
    networks:
      - teachergpt

networks:
  teachergpt:
    driver: bridge
