apiVersion: v1
kind: Secret
metadata:
  namespace: ${KUBERNETES_NAMESPACE}
  name: strapi-envs
type: Opaque
stringData:
  db_client: ${DB_CLIENT}
  db_host: ${DB_HOST}
  db_port: '${DB_PORT}'
  db_name: ${DB_NAME}
  db_user: ${DB_USER}
  db_password: ${DB_PASSWORD}
  db_ssl: 'false'
  redis_host: ${REDIS_HOST}
  redis_port: '${REDIS_PORT}'
  whisper_url: ${WHISPER_URL}
  openai_api_key: ${OPENAI_API_KEY}
  openai_gpt_model: ${OPENAI_GPT_MODEL}
  openai_whisper_model: ${OPENAI_WHISPER_MODEL}
  openai_embedding_model: ${OPENAI_EMBEDDING_MODEL}
  admin_jwt_secret: ${ADMIN_JWT_SECRET}
  jwt_secret: ${ADMIN_JWT_SECRET}
  app_keys: ${APP_KEYS}
  api_token_salt: ${API_TOKEN_SALT}
  base_url: https://${STRAPI_URL}
